# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c079c6354361fd5b162a48b83036bca3"
name = "smartpop"
handle = "smartpop-1"
app_url = "https://smartpop.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_script_tags,read_script_tags"

[auth]
redirect_urls = ["https://smartpop.vercel.app/auth/callback", "https://smartpop.vercel.app/auth/shopify/callback", "https://smartpop.vercel.app/api/auth/callback"]

[pos]
embedded = false
